### ISSUE TITLE
Extra margin/Horizontal Scrolling

### ISSUE THREAD

**Issue by melissamcewen** [Annauva/colmar-academy#2]
So I noticed this mystery margin here on some resolutions. 

![extra-margin](https://user-images.githubusercontent.com/1251094/37382078-b7b02a9e-270e-11e8-83e5-8b312796459c.png)
(This is using the device toolbar in Chrome Inspector https://developers.google.com/web/tools/chrome-devtools/device-mode/emulate-mobile-viewports
) 

Most of the time you don't want this because it can cause horizontal scrollbars which can cause a lot of issues with usability (unless you want horizontal scrollbars, which is rare)

I usually tackle this issue by hiding various sections with Chrome Inspector by adding the `display: none" to them. With this I identified `.thesis` and `.information` as the ones that had this issue. 

![displaynone](https://user-images.githubusercontent.com/1251094/37382135-19899ce6-270f-11e8-94e0-157ce499a3c0.png)

So what's causing this? Well it's the margins + the 100% width. With 100% width it will try to fit the entire thing into 100% of the screen including the margins. Using padding instead will solve this.

I use margins for when I need outside space and padding when I need inside and I think padding is going to be the right choice here since you need some space inside these containers not outside

**Comment by Annauva** [comment]
Aa yes, I seem to have a problem with getting padding and margin mixed together! Thanks for noticing, I'll work on it!
